# Generated by Django 5.1.6 on 2025-02-28 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sarmika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=18, null=True)),
                ('work', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thakedar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SarmikaAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thakedar.sarmika')),
            ],
        ),
        migrations.CreateModel(
            name='SermikaVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePhoto', models.ImageField(upload_to='profile/')),
                ('IdProof', models.ImageField(upload_to='idproof/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thakedar.sarmika')),
            ],
        ),
        migrations.AddField(
            model_name='sarmika',
            name='tid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thakedar.thakedar'),
        ),
        migrations.CreateModel(
            name='ThakedarAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thakedar.thakedar')),
            ],
        ),
        migrations.CreateModel(
            name='ThakedarVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePhoto', models.ImageField(upload_to='profile/')),
                ('IdProof', models.ImageField(upload_to='idproof/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thakedar.thakedar')),
            ],
        ),
    ]
