# Generated by Django 5.1.6 on 2025-02-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thakedar', '0002_remove_thakedarverify_owner_thakedarverify_tid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SermikaVerify',
            new_name='SarmikaVerify',
        ),
    ]
