# Generated by Django 5.1.6 on 2025-02-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thakedar', '0003_rename_sermikaverify_sarmikaverify'),
    ]

    operations = [
    ]
